### ISSUE TITLE
mkN example in haddock doesn't work

### ISSUE THREAD

**Issue by l29ah** [Shimuuar/fixed-vector#10]
https://hackage.haskell.org/package/fixed-vector-1.1.0.0/docs/Data-Vector-Fixed.html

```
λ> v = mkN (Proxy @ (Int,Int,Int)) 1 2 3

<interactive>:30:16: error: parse error on input ‘@’
```

**Comment by Shimuuar** [comment]
It's `TypeApplications` which should be enabled. I added mention of this extension in 9cf0e24a5f9c2071ae81b07521c9b867a42f648f
