### ISSUE TITLE
any erroneously returns true

### ISSUE THREAD

**Issue by thmeek1** [Shimuuar/fixed-vector#18]
The any function always seems to return true. 

test case:
```
λ> :set -XDataKinds -package fixed-vector
λ> import Data.Vector.Fixed as V
λ> import Data.Vector.Fixed.Unboxed as UV
λ> v = V.fromList [4,1,2] :: UV.Vec 3 Int
λ> V.any (< 0) v
True
λ> V.any (> 99) v
True
```

This is using GHC version 9.2.4.

The following line should be changed to `any f = foldr (\x b -> f x || b) False`
https://github.com/Shimuuar/fixed-vector/blob/f00a9d2b0af66a8aeb82583f3af7945210cbee74/fixed-vector/Data/Vector/Fixed/Cont.hs#L1027

**Comment by Shimuuar** [comment]
I've uploaded 1.2.1.1 with bug fix. Thank you!
